name: Node.js CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout main branch
      uses: actions/checkout@master
      with:
        ref: main
        path: src
    - name: Checkout builds branch
      uses: actions/checkout@master
      with:
        ref: builds
        path: builds
    - uses: pnpm/action-setup@v2
    - name: Change directory to src
      run: cd src
    - name: Use Node.js 17
      uses: actions/setup-node@v2
      with:
        node-version: 17
        cache: 'pnpm'
    - name: Install dependencies
      run: pnpm install
    - name: Build aliucord
      run: pnpm build
    - name: Upload dist folder as artifact
      uses: actions/upload-artifact@v3
      if: github.ref != format('refs/heads/{0}', github.event.repository.default_branch)
      with:
        name: dist
        path: dist/*
    - name: Upload dist folder to builds branch
      if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
      run: |
        cd $GITHUB_WORKSPACE/builds
        cp ../src/dist/* .
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git pull
        git add -A
        git commit -m "Build $GITHUB_SHA"
        git push
